[[install]]
== Install {kib}

[float]
=== Hosted {kib}

If you are running our hosted Elasticsearch Service on Elastic Cloud, you access Kibana with a single click. (You can {ess-trial}[sign up for a free trial] and start exploring data in minutes.)

[[supported-platforms]]
[float]
== Supported platforms

Packages of Kibana are provided for and tested against Linux, Darwin, and
Windows. Since Kibana runs on Node.js, we include the necessary Node.js
binaries for these platforms. Running Kibana against a separately maintained
version of Node.js is not supported.

[float]
[[elasticsearch-version]]
== Elasticsearch version

Kibana should be configured to run against an Elasticsearch node of the same
version. This is the officially supported configuration.

Running different major version releases of Kibana and Elasticsearch (e.g.
Kibana 5.x and Elasticsearch 2.x) is not supported, nor is running a minor
version of Kibana that is newer than the version of Elasticsearch (e.g. Kibana
5.1 and Elasticsearch 5.0).

Running a minor version of Elasticsearch that is higher than Kibana will
generally work in order to facilitate an upgrade process where Elasticsearch
is upgraded first (e.g. Kibana 5.0 and Elasticsearch 5.1). In this
configuration, a warning will be logged on Kibana server startup, so it's only
meant to be temporary until Kibana is upgraded to the same version as
Elasticsearch.

Running different patch version releases of Kibana and Elasticsearch (e.g.
Kibana 5.0.0 and Elasticsearch 5.0.1) is generally supported, though we
encourage users to run the same versions of Kibana and Elasticsearch down to
the patch version.

[float]
=== Install {kib} yourself

NOTE: Starting with version 6.0.0, Kibana only supports 64 bit operating systems.

Kibana is provided in the following package formats:

[horizontal]
`tar.gz`/`zip`::

The `tar.gz` packages are provided for installation on Linux and Darwin and are
the easiest choice for getting started with Kibana.
+
The `zip` package is the only supported package for Windows.
+
<<targz>> or <<windows>>

`deb`::

The `deb` package is suitable for Debian, Ubuntu, and other Debian-based
systems.  Debian packages may be downloaded from the Elastic website or from
our Debian repository.
+
<<deb>>

`rpm`::

The `rpm` package is suitable for installation on Red Hat, SLES,
OpenSuSE and other RPM-based systems.  RPMs may be downloaded from the
Elastic website or from our RPM repository.
+
<<rpm>>

`docker`::

Images are available for running Kibana as a Docker container. They may be
downloaded from the Elastic Docker Registry.
+
<<docker,Running Kibana on Docker>>

IMPORTANT: If your Elasticsearch installation is protected by
{ref}/elasticsearch-security.html[{stack-security-features}] see
{kibana-ref}/using-kibana-with-security.html[Configuring security in {kib}] for
additional setup instructions.

include::install/targz.asciidoc[]

include::install/windows.asciidoc[]

include::install/deb.asciidoc[]

include::install/rpm.asciidoc[]

include::{kib-repo-dir}/setup/docker.asciidoc[]
